### PR TITLE
Add Awesome List Section and Update Leadership on OSR Microsite

### PR DESCRIPTION
**Pull request by mcleo-d**
## Description
This PR updates the OSR `docusaurus` microsite and SIG documentation to create an `Awesome List` category. All previous `H1` resource sections have been split into their own individual pages for easier additions and updates.

## Updated Project Taxonomy
```
{
  "docs": {
    "General": [
      "meetings",
      "about"
    ],
    "Awesome Lists": [
      "awesome-lists/resources",
      "awesome-lists/external-resources",
      "awesome-lists/trainings"
    ]
  }
}
```

## Documentation Leadership Update
The pull request also updates the SIG leadership on `docs/about` to reflect the following for SIG discussion at https://github.com/finos/open-source-readiness/issues/26.

```
## Leadership

### OSR SIG Chair

### FINOS OSR Lead
```

### CODE REVIEW

**Review by psmulovics — APPROVED** [review]

**Comment by psmulovics** [comment]
@vmbrasseur 's feedback is to use a different wording than 'awesome list'

**Comment by vmbrasseur** [comment]
Comments from #26 

* VMB dislikes the name "awesome lists" (Peter agrees, as does a community member))
* People like the reorg of the information, though

**Comment by mcleo-d** [comment]
@vmbrasseur and @psmulovics,

I have renamed the `awesome-list` section to `osr-resources` that best reflects the content within the section. Please find the pre-deploy change here ... https://deploy-preview-27--open-source-readiness.netlify.app/docs/osr-resources/resources

It would be great to get your approval as I would like to use the [training section](https://deploy-preview-27--open-source-readiness.netlify.app/docs/osr-resources/trainings) to help answer the question from @troups here ... https://github.com/finos/open-source-readiness/pull/29#discussion_r844093736

Many thanks 🌟 

James.

**Review by vmbrasseur — APPROVED** [review]
Much better name!

**Comment by vmbrasseur** [comment]
Approved and merged.

**Pull request merged**
