### PR TITLE
Created a Learning Path for the COSD Certification

### PR DESCRIPTION
**Pull request by robmoffat**
... which is still TBD

### CODE REVIEW

**Comment by robmoffat** [comment]
We've finished the JTA for the certification now so I'm fairly confident that the courses in this learning path are the correct ones to do to help you on your way with the exam.

Main thing to review is this page:

https://deploy-preview-156--open-source-readiness.netlify.app/docs/bok/Certifications/COSD

**Comment by robmoffat** [comment]
Still waiting for the course code and exam blueprint page.

**Comment by robmoffat** [comment]
@finos/osr-maintainers please take a look - added in the details of our learning path with links to the new training and certification.

- [Front Page](https://deploy-preview-156--open-source-readiness.netlify.app/docs/welcome)
- [Training Page](https://deploy-preview-156--open-source-readiness.netlify.app/docs/osr-resources/Training)
- [LFD137 Page](https://deploy-preview-156--open-source-readiness.netlify.app/docs/bok/Training/LFD137-Contribution-In-Finance)
- [FSOSD](https://deploy-preview-156--open-source-readiness.netlify.app/docs/bok/Certifications/FSOSD)

**Comment by psmulovics** [comment]
Wow, this is REALLY great, well done!

**Review by psmulovics — APPROVED** [review]

**Pull request merged**
