### PR TITLE
Openchain

### PR DESCRIPTION
**Pull request by robmoffat**

### CODE REVIEW

**Comment by robmoffat** [comment]
Requesting Shane Coughlan's review before merge

**Comment by robmoffat** [comment]
https://deploy-preview-231--open-source-readiness.netlify.app/docs/bok/Artifacts/OpenChain-LicenseCompliance

https://deploy-preview-231--open-source-readiness.netlify.app/docs/bok/Artifacts/OpenChain-SecurityAssurance

**Comment by shanecoughlan** [comment]
Ping to check when this will merge?

**Comment by robmoffat** [comment]
Discussed in yesterday's meeting - can someone approve?

**Review by psmulovics — APPROVED** [review]

**Pull request merged**
