### PR TITLE
Compliant Open Source Consumption

### PR DESCRIPTION
**Pull request by robmoffat**
@jstclair2019 @rhyddian @andybs

Work in progress

### CODE REVIEW

**Review by jstclair2019 — COMMENTED** [review]
Added additional regulations

**Comment by robmoffat** [comment]
Compliance for Consumption article preview: 

https://deploy-preview-115--open-source-readiness.netlify.app/docs/bok/Activities/Level-2/Consumption-Compliance

Firewalls: 

https://deploy-preview-115--open-source-readiness.netlify.app/docs/bok/Artifacts/Firewalls

@psmulovics would love your review of this second one

**Review by eddie-knight — APPROVED** [review]

**Comment by psmulovics** [comment]
Provided my comments on the firewall offline (online?)

**Review by psmulovics — APPROVED** [review]

**Comment by robmoffat** [comment]
These items: 

- [ ] How to set up compliance-friendly processes for open source contributions
- [ ] OSS Policy is an extension of the SDLC Policy.  @jstclair2019 Review open ssf training
- [ ] how to move beyond compliance preventing behaviour, towards open source enabling better compliance (e.g OpenRegTech and CFI).  "If we can insert ourselves into the organisation at the control points, and add value, we can have a seat a the table. Technology success to implement controls will help this"

I think we need to cover in the next PR.

**Comment by jstclair2019** [comment]
>     * [ ]  OSS Policy is an extension of the SDLC Policy.  @jstclair2019 Review open ssf training
> 
>     * [ ]  how to move beyond compliance preventing behaviour, towards open source enabling better compliance (e.g OpenRegTech and CFI).  "If we can insert ourselves into the organisation at the control points, and add value, we can have a seat a the table. Technology success to implement controls will help this"
> 
> 
> I think we need to cover in the next PR.

Sounds good, happy to get something together by next week.

**Comment by robmoffat** [comment]
Well that would be awesome, obviously! 😁 

Sorry - I didn't mean to tag you there @jstclair2019, it's just I copied and pasted that stuff out of the top of the issue and didn't see your name in it.  

But if you have something to contribute I'd be very happy to have it (prob. best in a new PR)

**Pull request merged**
