### PR TITLE
Added results of OSMM Survey

### PR DESCRIPTION
**Pull request by robmoffat**

### CODE REVIEW

**Comment by robmoffat** [comment]
See: https://deploy-preview-297--open-source-readiness.netlify.app/docs/bok/OSMM/October-2024-Survey

**Comment by psmulovics** [comment]
Have we considered to HTML up the table instead of images?

**Comment by robmoffat** [comment]
> Have we considered to HTML up the table instead of images?

I'm not sure I have time right now, but if you wanted to have a crack at it the sources are here: 

https://docs.google.com/spreadsheets/d/10wT3cY80-gU2bVBqqdZ2I0Aux4TfR1q4Jz2KhXGOc7g/edit?gid=819045659#gid=819045659

**Comment by psmulovics** [comment]
Let's merge it this way, I have more or less the working HTML together but needs some more theming

**Review by psmulovics — APPROVED** [review]

**Pull request merged**
