### PR TITLE
InnerSource

### PR DESCRIPTION
**Pull request by robmoffat**

### CODE REVIEW

**Comment by robmoffat** [comment]
Hi @BrittanyIstenes maybe take a look at this: https://deploy-preview-238--open-source-readiness.netlify.app/InnerSource

**Review by BrittanyIstenes — APPROVED** [review]
Looks good and I am comfortable with merging

**Comment by psmulovics** [comment]
It needs to be rebased

**Comment by robmoffat** [comment]
I'll look at this when I come back next week

**Pull request merged**
