### PR TITLE
Victor strategy

### PR DESCRIPTION
**Pull request by robmoffat**

### CODE REVIEW

**Comment by robmoffat** [comment]
Please see:
https://deploy-preview-239--open-source-readiness.netlify.app/docs/presentations/Strategy
and added Victor here:
https://deploy-preview-239--open-source-readiness.netlify.app/docs/about

**Comment by robmoffat** [comment]
@victorjunlu please review

**Comment by victorjunlu** [comment]
Looks good. Thanks.

**Comment by robmoffat** [comment]
@psmulovics here's one you can merge 😄

**Review by psmulovics — APPROVED** [review]

**Pull request merged**
