### PR TITLE
Open Source Personas

### PR DESCRIPTION
**Pull request by robmoffat**
@caradelia I've started adding the content from your spreadsheet into the BoK pages.  Previews below

### CODE REVIEW

**Comment by robmoffat** [comment]
Two examples: 

https://deploy-preview-116--open-source-readiness.netlify.app/docs/bok/Roles/CEO

https://deploy-preview-116--open-source-readiness.netlify.app/docs/bok/Activities/Level-2/License-Management

**Comment by psmulovics** [comment]
Visually and content wise - looks awesome, nice work the two of you!

**Review by psmulovics — APPROVED** [review]

**Comment by caradelia** [comment]
Looks great. Great to continue with the others. Thanks @robmoffat!

**Comment by robmoffat** [comment]
Ok, I've done the others:

https://deploy-preview-116--open-source-readiness.netlify.app/docs/bok/Roles/Introduction

- I think SREs should really be an aspect of an Operations role.
- I've lumped Security Expert / CISO together, I think they're basically in the same area.
- I am missing `Corporate Communications/Marketing` and `InternalAudit` - would be good to have some notes on those.
- There are a few blanks here and there where I haven't got some bits of information. Please review!

**Pull request merged**
