### PR TITLE
Software Licenses/CLAs and DCOs

### PR DESCRIPTION
**Pull request by robmoffat**
First draft of CLA/DCO article, factored out License stuff Into it's own file.

### CODE REVIEW

**Comment by robmoffat** [comment]
Please check out:
 - Artifacts/Software Licenses
 - Artifacts/CLAs And DCOs

**Comment by brooklynrob** [comment]
@robmoffat This looks really good.

Re ICLAs ... I'm not sure if the scope of this bok is just FINOS (and perhaps wider LF) or open source more broadly. If the latter, it's worth nothing that some foundations -- ASF and Trino are two - require folks named to CCLA Schedule As to ALSO do ICLAs. Developers needs to be covered *by both* (which of course doubles the administration and records burden for OSPOs). Different rationales as I recall -- I think in the case of ASF it's that there tooling only can do checks for ICLA coverage so it's a tooling work around. In the case of Trino I think it's that they want coverage in the case someone leaves an org and continues to contribute independently.

It's also worth nothing that while CCLAs == corporation holds the copyright (i.e., owns the IP, likely as a function of the invention clause in an employee's employment agreement), in some ICLAs they are written to catch both the individual as the copyright owner AND their employer as copyright holder. See the following from the ASF ICLA "'You' (or 'Your') shall mean the copyright owner or legal entity authorized by the copyright owner that is making this Agreement with the Foundation." This is why/how some foundations use ICLAs in place of CCLAs even for corporate contributions. 

May also be worth contrasting a CCLA Schedule A and DCO by their order of operations. Getting added to a CCLA Schedule A is a more heavy weight, up front activity in which another person from an org other than the developer themselves needs to explicitly authorize the developer. The DCO, by contract, is a pinky promise by a developer that their employer has approved them. The former is closed loop, explicit, and synchronous (and more heavy weight as a result); the latter is not. Yes, DCOs are "easier", but they are not without risk -- if it turns out a developer in fact did NOT have permission to contribute (or may just didn't understand what they were signing), and then contributed something they should not have, there could be complex and expensive unwinding of the contribution that would need to occur, that could even lead to litigation. That isn't to say DCOs are bad -- but they are not without their own risks, and most organizations are likely going to want to track which of their developers have made contribution via a DCO for myriad compliance and audit reasons.

**Comment by robmoffat** [comment]
>  In the case of Trino I think it's that they want coverage in the case someone leaves an org and continues to contribute independently. 

Actually that's quite a good mitigation of the issue I brought up in the article.  At least until the person joins another firm, at which point that firm could assert copyright over further commits.  Is this better?  Seems like it just pushes the problem down the road.

>  in some ICLAs they are written to catch both the individual as the copyright owner AND their employer as copyright holder.

Doesn't that effectively mean that the individual is granting rights on behalf of their organisation?

Your third paragraph I think provides really useful additional context for the DCO vs CLA part and I'll add this in.

**Review by psmulovics — APPROVED** [review]

**Review by psmulovics — APPROVED** [review]

**Comment by robmoffat** [comment]
> individual is granting rights on behalf of their organisation?

I've updated the doc to answer my own question:  in Apache's eyes the CCLA is actually an agreement between the company and the contributor.

**Pull request merged**
