### PR TITLE
Using Open Source

### PR DESCRIPTION
**Pull request by robmoffat**

### CODE REVIEW

**Comment by robmoffat** [comment]
https://deploy-preview-250--open-source-readiness.netlify.app/docs/bok/Activities/Level-1/Using

**Comment by robmoffat** [comment]
Hi @caradelia,

It's best if we just use the code review tools built into GitHub for this

**Comment by robmoffat** [comment]
@finos/osr-maintainers can we get this approved?

**Comment by robmoffat** [comment]
@psmulovics @BrittanyIstenes @caradelia @coopernetes 

Had feedback from Madlen on this - it's ready to go

**Review by psmulovics — APPROVED** [review]

**Pull request merged**
