### PR TITLE
Add analytics on osr.finos.org

### PR DESCRIPTION
**Pull request by maoo**
Let's see if the netlify build works and the preview contains the gtag code; to populate the Google Analytics dashboard, we'd have to merge the PR first

### CODE REVIEW

**Comment by maoo** [comment]
@robmoffat - not sure why the Netlify preview is not working; could you please have a look at this PR ? Thanks!

**Review by psmulovics — COMMENTED** [review]
I think you need to add it properly with npm install --save, so the lock files would be updated too.

**Comment by maoo** [comment]
> https://app.netlify.com/sites/reliable-medovik-8e47e9/deploys/65dda2a4136cf600081bb037

ok, this is weird; the Netlify instance that dropped this comment is NOT the FINOS one, and I don't have access to it. @robmoffat @psmulovics - do you know anything about this?

Screenshot 2024-02-27 at 09 57 32

Re. the PR, the GTag code is there, see view-source:https://deploy-preview-242--open-source-readiness.netlify.app/opensourcereadiness ; I think this is ready to merge, wdyt?

**Review by robmoffat — APPROVED** [review]

**Comment by mimiflynn** [comment]
> > https://app.netlify.com/sites/reliable-medovik-8e47e9/deploys/65dda2a4136cf600081bb037
> 
> ok, this is weird; the Netlify instance that dropped this comment is NOT the FINOS one, and I don't have access to it. @robmoffat @psmulovics @mimiflynn - do you know anything about this?
> 
> Screenshot 2024-02-27 at 09 57 32
> Re. the PR, the GTag code is there, see view-source:https://deploy-preview-242--open-source-readiness.netlify.app/opensourcereadiness ; I think this is ready to merge, wdyt?

I recently got what appeared to be a netlify invite and did some mindless clicking (I am the weakest link) could that have impacted this project?

**Comment by maoo** [comment]
> I recently got what appeared to be a netlify invite and did some mindless clicking (I am the weakest link) could that have impacted this project?

Yes, this could be a Netlify.com app linked to this repo; could you access netlify.com and see if you have any site called `reliable-medovik` ? If so, could you delete it? You can always rely on PR previews generated by the FINOS Netlify instance. Thanks!

**Comment by mimiflynn** [comment]
> > I recently got what appeared to be a netlify invite and did some mindless clicking (I am the weakest link) could that have impacted this project?
> 
> Yes, this could be a Netlify.com app linked to this repo; could you access netlify.com and see if you have any site called `reliable-medovik` ? If so, could you delete it? You can always rely on PR previews generated by the FINOS Netlify instance. Thanks!

Done! So crazy, I don't know how all that happened. Sorry!

**Comment by maoo** [comment]
Thanks @mimiflynn !

**Pull request merged**
