### PR TITLE
About page bios

### PR DESCRIPTION
**Pull request by robmoffat**
Please give me your Bios to add to this page!

### CODE REVIEW

**Comment by psmulovics** [comment]
Mr. Peter Smulovics studied Technical Informatics, Business Telecommunication, Software Techniques and Specification and Financial Informatics, had his thesis about Increasing Efficiency of Multi Protocol Label. Switching Routing Algorithms using Simulated Annealing; Enterprise Templates and Domain Specific Languages – Enabling Modification of Visual Studio.NET IDEs to Comply with Company Standards and to Enhance Developer Productivity and Object-Relational Mapping in .NET 1.0.

He is a publicist for IDG and for Architecture Journal; author and co-author of several books about OLAP, Mobile Architectures, IDEs, Frontend development, 4th and 5th generation languages, etc.; a returning presenter on TechEd, DevDays, Techready, Agile DevCon, TechNet etc.

He is a founder member of AgileAlliance, Architecture Forum, Architect Academy and .NET forum, Technical Lead on several OSS projects like Novell/JBoss’ Hibernate, Apache Velocity and similar. He is Microsoft, Ariba, JBoss, and SiteCore certified and also a trainer on several technologies.

He has been working in IT since 1995, has project experience in vast majority in fields (FMCG, public, financial, energy, telecom, pharmaceutical, mobile, music, security). He worked as Oracle DBA at Compaq, Lead Software Design Engineer at Microsoft (working on C#, .NET, Dynamics, Visual Studio .NET, SQL Server, Office, ASP.NET, Entity Framework, Azure, etc), Lead Developer for Intesa Sanpaolo’s Account Management System, Lead Developer for Vodafone for their Invoicing System, Lead Developer with Deutsche Telekom’s Digital Asset Management solution.

He is currently an Executive Director of Enterprise Application Infrastructure focusing on Microsoft technologies at Morgan Stanley.

**Comment by caradelia** [comment]
Cara Delia Bio:
Advocating open source principles and practices by contributing to external open source communities focused on Financial Services and Climate Sustainability at Red Hat. Community leadership includes: FINOS Open Source Readiness Co-Chair, FINOS Technical Steering Committee and Technical Lead and founding charter member for the CNCF Environmental Sustainability technical advisory group (TAG).

**Comment by psmulovics** [comment]
I'd wait for all bios / pictures to be added before merging.

**Comment by psmulovics** [comment]
> I'd wait for all bios / pictures to be added before merging.

So only the executive sponsors are missing :) @rhyddian

**Comment by robmoffat** [comment]
I've just sent @chrisjstevo and @rhyddian asking them for the missing details...

**Comment by robmoffat** [comment]
maybe we should merge this anyway?

**Review by psmulovics — APPROVED** [review]

**Pull request merged**
